When a metal wire segment is fabricated it can act as an antenna. Reactive iron etching causes charge to accumulate on the wire. Transistor gates can be damaged during fabrication. There are two solutions for it the first one is to do bridging which attaches a higher layer intermediary that requires router awareness. Adding antenna diode cells to leak away the charges these cells are provided by the S  C  L. The other solution is to adopt fake and dinner diode next to every cell input after placement then we could run the antenna checker magic on the routed layout if the checker reports a violation on the cell input then we have to replace the fake diode by a real one. Magic is used for designing rules checking and spice extraction from layout. Magic and Netgen are used for L V S.                                             
now let us learn how to define wit and height of core and a dye. First, let us begin with a netlist we have two flip flops and a combinational logic in between them. while defining a chip's dimensions, we mostly depend on the size of the combinational logic or the gates and the flip-flops. Firstly we will give the combinational logic and the flip flops respective breadth and height Then we are mostly interested in the dimensions of these standard cells. Let us take an example that a standard cell has a width and breadth of one unit by one unit thus the area will be one square unit we will calculate this entire area which will determine the width and height and the area of our chip. Let us take we have 2 flip flops and 2 gates each will have a width and height of 1 unit thus each of them has an area of 1 square unit therefore if we place them our total area will be 4 square units. So now we have a rough dimension or the rough area of our chip we are not omissing the wires into this right now. This is the minimum area that will be occupied by the netlist. When the entire area of a core is utilized and no free area is left it is known as 100 percent utilization or utilization factor = 1. The utilization factor is equal to the area occupied by the netlist divided by the total area of the core And the aspect ratio is height divided by width. If the utilization factor is 1 it means the chip is square if it is something like 0.5 it means that the chip is a rectangle.
the next step is to define the locations of the preplaced cells. To understand what is a preplaced cell let us first assume that we have a combinational logic and that the combinational logic has some amount of function. like it is the multiplier half adder full adder etc. First, we will remove a part of our main circuit, cut it in half, and place the two pieces on a block. Finally, we will connect the two blocks using wires. Next, we will extend the IO pins. we will black box these boxes. Then we will separate the black boxes into different IP modules. Similarly, there are other IPs' also available for example we have Memory, Clock Gating Cells, comparator, mux, etc. The arrangement of these IPs' in a chip is referred to as Floorplanning. These IPs'/blocks have user-defined locations, and hence are placed in a chip before automated placement and routing and are called - pre-placed cells. Automated placement and routing tools place the design's remaining logical cells onto one chip. Once they are placed, their location is fixed they're permanent, The further steps will not touch their location. There is also one more important thing that we have to book which is to surround the preplaced cells with Decoupling capacitors. Consider capacitance to be zero for the discussion RDD, RSS, IDD, and LSS are well-defined values. During switching operation a circuit demands switching current which means peak current or "Ipeak", now due to the presence of RDD and LDD there will be a voltage drop across them, and the voltage at node A would be VDD' instead of VDD. If VDD' goes below the noise margin, due to RDD and LDD, the logic one at the output of the circuit won't be detected as logic one at the input of the circuit following this circuit.  
The next important step is to bind netlist with physical cells. We will give each component of the netlist their own dimensions. These are present in shelves and let us call that a library. A library can be of two types one that contains the shape and the other that contains the information.  A library is a place where the standard cells are kept. Standard cells contain gates like - and gate, or gate, buffer, inverter, dff, latch, ICG, flip flops, etc.
There are two types of transistors CMOS and NMOS, to create a CMOS transistor we first select the substrate is selected usually a P-type Substrate is selected The resistance is usually high in the range of 5~50 ohms With doping level of 10 to the power of 13 cm3 with the orientation of 100. Substrate doping should be less than 'well' doping. Then the next step is to select that active area for transistors. Firstly, we will create isolation between each socket, then  deposit a layer of Silicon dioxide Of about 40 nm Next we will deposit a layer of silicon nitride of about 80 nm.  Then, 1um of photoresist is deposited, which will create the MASK 1, Then it is treated with UV light, and then the silicon nitrate will be etched, Then the photoresist is removed through chemicals. It is placed into a furnace, and field oxide is grown, this process is called 'LOCOS' Or local oxidation of silicon. silicon nitrate is then removed with hot phosphoric acid. Then we will create a gate area. The P-well, N-well, and p-type substrate is formed. This is how  a CMOS transistor is created.  

NOTE -- Flip Flop Ratio = Number of DFFs divided by the Number of cells * 100

By sloving this we get 1613 / 18036 * 100The other option is to view the results of the synthesis from the `synthesis` file in `picorv32a`. And to look the clock timing we can go to the `reports` folder. Then we will run the floorplan by the command `run_floorplan`.But before that, we have to set the variables. And to review the floorplan in Magic, use the command - `Magic -T/home/vsduser/Desktop/work/tools/openlane_working_dir/pdks/sky130A/libs.tech/magic/sky130A.tech lef read ../../tmp/merged.lef def read picorv32a.floorplan.def & ` In magic, `S` key is to select `V` key to center and `Z` key to zoom, the pins will be equally distanced from each other, like the image
![image](https://github.com/JustVanillaCode/VSD-ASIC-Level-Repository/assets/162819270/d23d0738-4fce-49ad-93fa-242984f80733)

. The next step is to run placement by the `run_placement` command. It does 3 functions -
1. Gloobal Placement by using RePlace tool.
2. Optimization by Resier tool.
3. Detailed Placement by OpenDP tool.
After running the placement the output in magic looks like -

![image](https://github.com/JustVanillaCode/VSD-ASIC-Level-Repository/assets/162819270/117fffb0-ee89-4669-9f61-c898ee42714a)

Labs for CMOS
It's possible to change OpenLANE configurations within the shell itself, on the go. Normally, IO Mode is set to random equidistant. However, we can change this by using the following command after floorplan: "set::env(FP_IO_MODE) 2". Once this command is executed, the IO pins will no longer be equidistant in mode 2 (which is different from the default mode 1).
After this, we may run the floorplan to check whether or not are the IO pins placed in the Hungarian alg's way i.e. stacked on one another 

![image](https://github.com/JustVanillaCode/VSD-ASIC-Level-Repository/assets/162819270/01d8ca21-c3a3-42bc-b3ea-8502a2141a55)
